In [0]:
import tensorflow as tf
import random
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [0]:
data = pd.read_csv("race.csv",encoding='utf-8')
#print(len(data))=70544
y = data['record']
X = data.loc[:, ["code","lane","sex","age","jockey_w","jockey","dandivi","yeondivi"
                    ,"s1f","c3","c4","g3f","g1f","cure_in_1m",
                 "weight_diff","raw_weight","weight_added","prev1_velo","horse_level_num"]]
#print(X.shape)
sex_mod = pd.get_dummies(X['sex'])
X = X.join(sex_mod)
X = X.drop(columns=['sex'])
#print(X.columns)
X = X.as_matrix()

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
train_size = len(X_train)
print("trains_size : ",train_size)
size_x = len(X_train[0])
print("size_x : ",size_x)
learning_rate = 0.001
training_epochs = 15
batch_size = 100
print(X_test)

trains_size :  49380
size_x :  21
[[3.5223e+04 6.0000e+00 3.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.8232e+04 3.0000e+00 4.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [3.5892e+04 1.0000e+01 4.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 ...
 [3.2214e+04 1.0000e+01 4.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [2.5347e+04 2.0000e+00 6.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [2.8625e+04 1.0000e+00 4.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]]


In [0]:
tf.reset_default_graph()

X = tf.placeholder(tf.float32, [None, size_x])
Y = tf.placeholder(tf.float32, [None, 1])


W1 = tf.get_variable(shape=[size_x, 256], name='weight1', initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([256]))
layer1 = tf.nn.relu(tf.matmul(X, W1) + b1)


W2 = tf.get_variable(shape=[256, 64], name='weight2', initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([128]))
layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)


W3 = tf.get_variable(shape=[64, 1], name='weight4', initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([1]))
hypothesis = tf.matmul(layer2, W3) + b3

cost = tf.losses.mean_squared_error(labels=Y, predictions=hypothesis)
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
